// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNpGrY_jJ9P6AAfrx2cjr06J3MnuA9n6s',
    appId: '1:330171692756:web:3cec318c635f3d1ec96d41',
    messagingSenderId: '330171692756',
    projectId: 'recipe210504-recipeproject',
    authDomain: 'recipe210504-recipeproject.firebaseapp.com',
    storageBucket: 'recipe210504-recipeproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfvyINwBx0LapTYgrTzETuKUxi_KgjdUw',
    appId: '1:330171692756:android:e6bfd2039bb98aa0c96d41',
    messagingSenderId: '330171692756',
    projectId: 'recipe210504-recipeproject',
    storageBucket: 'recipe210504-recipeproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8pAw616uYkt8FFNjXgwixzaniJHFM1iM',
    appId: '1:330171692756:ios:3c248a944b9ffe17c96d41',
    messagingSenderId: '330171692756',
    projectId: 'recipe210504-recipeproject',
    storageBucket: 'recipe210504-recipeproject.firebasestorage.app',
    iosBundleId: 'com.example.recipePage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8pAw616uYkt8FFNjXgwixzaniJHFM1iM',
    appId: '1:330171692756:ios:3c248a944b9ffe17c96d41',
    messagingSenderId: '330171692756',
    projectId: 'recipe210504-recipeproject',
    storageBucket: 'recipe210504-recipeproject.firebasestorage.app',
    iosBundleId: 'com.example.recipePage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNpGrY_jJ9P6AAfrx2cjr06J3MnuA9n6s',
    appId: '1:330171692756:web:2b588510f31c2b05c96d41',
    messagingSenderId: '330171692756',
    projectId: 'recipe210504-recipeproject',
    authDomain: 'recipe210504-recipeproject.firebaseapp.com',
    storageBucket: 'recipe210504-recipeproject.firebasestorage.app',
  );
}
